name: PyGlide the Notebook

on:
  push:
    branches:
      - main
    paths:
      - "**.ipynb"

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install requirements and dependencies
      run: |
        pip install jupyter
        pip install nbconvert
        pip install -e pyglide 

    - name: Run Jupyter Notebook and pyglide
      run: |
        for file in ${{ steps.list_files.outputs.files }}; do
          notebook_name="${file%.*}"  # Remove the .ipynb extension
          pyglide $GITHUB_WORKSPACE/${notebook_name}
        done
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add output.ipynb
        git commit -m "Auto-generated notebook output"
        git push
      working-directory: ${{ github.workspace }}
